#!/bin/sh
### BEGIN INIT INFO
# Provides:          iptables
# Required-Start:    $network
# Required-Stop:     $network
# Default-Start:     S
# Default-Stop:      0 6
# Short-Description: Custom Firewall
# Description:       
#
### END INIT INFO

#
# Author: Yoel Antonio Duran Diaz <yoet92@gmail.com>
# Git: https://github.com/yoet92/iptables.git
#

#==========================VARIABLES=================================#

# Binario de IPTABLES
IPTABLES=/sbin/iptables

# INTERFACES
# WAN
EXT_IF=ethx
EXT_IP=xxx.xxx.xx.x

# LAN
LAN_IF=ethx
LAN_IP=xxx.xxx.xx.x
LAN_RED=xxx.xxx.xx.x/xx

# loopback
LOO_RED=127.0.0.0/8

# Cualquier red
ANY_RED=0.0.0.0/0

# Proxy externo
PROXY_EXT=xxx.xxx.xx.x

#==========================START=====================================#
start_rules() {
# Limpiar reglas existentes
$IPTABLES -F
$IPTABLES -X
$IPTABLES -Z
$IPTABLES -t nat -F

$IPTABLES -P INPUT DROP
$IPTABLES -P FORWARD DROP
$IPTABLES -P OUTPUT DROP

echo 1 > /proc/sys/net/ipv4/ip_forward

$IPTABLES -A FORWARD -p tcp --sport 137:139 -o $EXT_IF -j DROP
$IPTABLES -A FORWARD -p udp --sport 137:139 -o $EXT_IF -j DROP
$IPTABLES -A OUTPUT  -p tcp --sport 137:139 -o $EXT_IF -j DROP
$IPTABLES -A OUTPUT  -p udp --sport 137:139 -o $EXT_IF -j DROP

# Bloquear uso del Proxy externo a LAN_RED
$IPTABLES -A FORWARD -i $LAN_IF -s $LAN_RED -d $PROXY_EXT -j DROP

for MAC in `cat /etc/mac`; do
$IPTABLES -A FORWARD -i $LAN_IF -m mac --mac-source $MAC -j ACCEPT
$IPTABLES -A INPUT  -s $LAN_RED -i $LAN_IF -m mac --mac-source $MAC -j ACCEPT
$IPTABLES -t nat -A PREROUTING  -i $LAN_IF -m mac --mac-source $MAC -j ACCEPT
done

$IPTABLES -A OUTPUT -o $LAN_IF -s $LAN_IP -j ACCEPT
$IPTABLES -A OUTPUT -o $EXT_IF -s $EXT_IP -j ACCEPT

#NAT
$IPTABLES -t nat -A POSTROUTING -s $LAN_RED -o $EXT_IF -j MASQUERADE

#lo
$IPTABLES -A INPUT  -i lo -s $LOO_RED -d $LOO_RED -j ACCEPT
$IPTABLES -A OUTPUT -o lo -s $LOO_RED -d $LOO_RED -j ACCEPT
$IPTABLES -t nat -A POSTROUTING -o lo -s $LOO_RED -j ACCEPT

#DNS
$IPTABLES -A INPUT  -s $ANY_RED -i $EXT_IF -p udp -m udp --sport 53 --dport 1024:65535 -j ACCEPT
$IPTABLES -A OUTPUT -d $ANY_RED -o $EXT_IF -p udp -m udp --dport 53 --sport 1024:65535 -j ACCEPT

#NTP
$IPTABLES -A INPUT  -p udp -m udp --dport 123 -i $EXT_IF -s $ANY_RED -j ACCEPT
$IPTABLES -A OUTPUT -p udp -m udp --sport 123 -j ACCEPT

#ICMP
$IPTABLES -A INPUT -p icmp --icmp-type echo-request -m limit --limit 2/s -j ACCEPT
$IPTABLES -A OUTPUT -p icmp --icmp-type echo-request -m limit --limit 2/s -j ACCEPT
$IPTABLES -A INPUT -p icmp --icmp-type echo-reply -m limit --limit 2/s -j ACCEPT
$IPTABLES -A OUTPUT -p icmp --icmp-type echo-reply -m limit --limit 2/s -j ACCEPT
# Aceptamos redirecciones
$IPTABLES -A INPUT -p icmp --icmp-type redirect -m limit --limit 2/s -j ACCEPT
$IPTABLES -A OUTPUT -p icmp --icmp-type redirect -m limit --limit 2/s -j ACCEPT
# Aceptamos tiempo excedido
$IPTABLES -A INPUT -p icmp --icmp-type time-exceeded -m limit --limit 2/s -j ACCEPT
$IPTABLES -A OUTPUT -p icmp --icmp-type time-exceeded -m limit --limit 2/s -j ACCEPT
# Aceptamos destino inalcanzable
$IPTABLES -A INPUT -p icmp --icmp-type destination-unreachable -m limit --limit 2/s -j ACCEPT
$IPTABLES -A OUTPUT -p icmp --icmp-type destination-unreachable -m limit --limit 2/s -j ACCEPT

#INET
$IPTABLES -A OUTPUT -o $EXT_IF -p tcp -m state --state NEW,ESTABLISHED,RELATED -j ACCEPT
$IPTABLES -A INPUT  -i $EXT_IF -p tcp -m state --state ESTABLISHED,RELATED -j ACCEPT

$IPTABLES -A FORWARD -m state --state RELATED,ESTABLISHED -j ACCEPT

$IPTABLES -t nat -A PREROUTING  -m state --state RELATED,ESTABLISHED -j ACCEPT

$IPTABLES -t nat -A PREROUTING  -i $EXT_IF -d $EXT_IP -j ACCEPT
$IPTABLES -t nat -A PREROUTING  -m state --state RELATED,ESTABLISHED -j ACCEPT

$IPTABLES -t nat -A POSTROUTING -o $EXT_IF -s $EXT_IP -j ACCEPT
$IPTABLES -t nat -A POSTROUTING -m state --state RELATED,ESTABLISHED -j ACCEPT

$IPTABLES -t nat -A POSTROUTING -o $LAN_IF -s $LAN_RED -j ACCEPT

#-----
$IPTABLES -A INPUT -p tcp --dport 1:65535 -j DROP
#-----
#==========================LOGS=========/var/log/kern.log============#

#$IPTABLES -t nat -A PREROUTING  -j LOG --log-prefix "[FW - PR] "
#$IPTABLES -t nat -A POSTROUTING -j LOG --log-prefix "[FW - PO] "
#$IPTABLES -A FORWARD -j LOG --log-prefix "[FW - FW] "
#$IPTABLES -A INPUT -p tcp --dport 1:65535 -j LOG --log-prefix "[FW - IN] "
#$IPTABLES -A OUTPUT -j LOG --log-prefix "[FW - OU] "

echo "INICIADO"
}

#==========================STOP======================================#

stop_rules() {
$IPTABLES -F INPUT
$IPTABLES -F FORWARD
$IPTABLES -F OUTPUT
$IPTABLES -X
$IPTABLES -Z
$IPTABLES -t nat -F
$IPTABLES -P INPUT ACCEPT
$IPTABLES -P FORWARD ACCEPT
$IPTABLES -P OUTPUT ACCEPT

echo "DETENIDO"
}

#====================================================================#

case "$1" in
    start)
start_rules
apt moo
    ;;

    stop)
stop_rules
apt moo
    ;;
	restart)
echo "Restarting IPTABLES FIREWALL ..."
stop_rules
start_rules
apt moo
	;;
    *)
echo "Uso: $0 {start/stop/restart}"
    ;;

esac
:
